# River's Spelling Bee — the official Scripps "Two Bee" 4th-grade study list
# (50 words), source: "Spelling Bee Words" screenshot, 4th Grade Drive folder.
# Every definition is re-derived independently (the source is a bare word
# list, no definitions or examples to copy). Split into four lessons of the
# real 50, so each sitting is a manageable size; bee:true opts every lesson
# into the honeycomb flashcards and the "hear it, spell it" voice game.
from unit_common import card, q, build

SRC = "Spelling Bee Words — 2026-27 Scripps 'Two Bee' 4th Grade Study List (Drive)"
SRCLONG = ("Scripps National Spelling Bee, 2026-27 Two Bee Study Words for Fourth "
           "Grade — official 50-word study list (Drive)")

# Each entry: term, bold-lead definition, one example sentence, a spelling
# mnemonic (the card's memory hook — never a restatement of the meaning),
# a phonetic respelling, then the spell-question's steps (syllable/trouble-
# spot walkthrough) and a short verification tip.
WORDS = [
 dict(t='buttons', d='Small fastening discs sewn onto clothing that slip through a buttonhole to hold it closed.',
      ex='She counted six buttons down the front of the coat.',
      hint='Double T — BUT-tons, not one T.', sp='BUT-uns',
      steps=['Two syllables: but and tons.','The middle doubles the T: B-U-T-T.','Finish with O-N-S.'],
      tip='A single T would say "BYOO-tons" — the double T keeps the short U sound.'),
 dict(t='tiptoed', d='Walked quietly and carefully on the tips of the toes, to avoid making noise.',
      ex="She tiptoed past the sleeping baby's door.",
      hint='TIP + TOED — two small words hiding inside the big one.', sp='TIP-tohd',
      steps=['Two small words joined: tip and toed.','T-I-P, then T-O-E-D.','The "toe" keeps its E before the D.'],
      tip='"Toed" is "toe" plus D for past tense — the E does not drop.'),
 dict(t='cuddle', d='To hold someone or something closely and warmly, usually while sitting or lying down.',
      ex='The kitten liked to cuddle up in the blanket.',
      hint='Double D — CUD-dle, not one D.', sp='KUD-uhl',
      steps=['Two syllables: cud and dle.','The middle doubles the D: C-U-D-D.','Finish with L-E.'],
      tip='One D would make the U sound long, like in "food" — the double D keeps it short.'),
 dict(t='clever', d='Quick to think of smart ideas or solve problems in an original way.',
      ex='Her clever plan solved the puzzle in half the time.',
      hint='CLEV-er — one V, like most of "eleven".', sp='KLEV-er',
      steps=['Two syllables: clev and er.','C-L-E-V — just one V in the middle.','Finish with E-R.'],
      tip='No double letters anywhere in this one — it is shorter than it sounds.'),
 dict(t='puffy', d='Swollen, rounded, or puffed out — often used for clouds, eyes, or sleeves.',
      ex='Puffy white clouds drifted across the summer sky.',
      hint='Double F — PUFF, then Y.', sp='PUF-ee',
      steps=['Start with the word "puff": P-U-F-F.','Swap the silent nothing for a Y at the end.','P-U-F-F-Y.'],
      tip='"Puff" already has the double F — this word just adds a Y.'),
 dict(t='basement', d='The floor of a building that sits below ground level.',
      ex='The old trunks were stored in the basement.',
      hint='BASE + MENT — the base of the building, plus -ment.', sp='BAYS-ment',
      steps=['Two parts: base and ment.','B-A-S-E, keeping the silent E.','Add M-E-N-T.'],
      tip='The E in "base" stays even with -ment added after it.'),
 dict(t='burlap', d='A coarse, rough fabric woven from jute or hemp fibers.',
      ex='The potatoes were shipped to market in a burlap sack.',
      hint='Two syllables: BUR-lap — the "ur" sounds like "fur", not "ber".', sp='BUR-lap',
      steps=['Two syllables: bur and lap.','B-U-R, not B-E-R.','Finish with L-A-P.'],
      tip='Say "fur" in your head first — "bur" rhymes with it exactly.'),
 dict(t='wetlands', d='Low-lying land that is soaked with water for all or part of the year, like a marsh or swamp.',
      ex='Herons and turtles both make their homes in the wetlands.',
      hint='WET + LANDS — land that stays wet.', sp='WET-landz',
      steps=['Two small words: wet and lands.','W-E-T, then L-A-N-D-S.','No joining letters needed — just put them together.'],
      tip='Both halves are words you already know how to spell on their own.'),
 dict(t='invite', d='To ask someone to come to an event or to take part in something.',
      ex='They plan to invite the whole class to the party.',
      hint='IN- + -VITE, like "invitation" with the ending cut off.', sp='in-VYT',
      steps=['Two syllables: in and vite.','I-N, then V-I-T-E.','The silent E at the end makes the I say its own name.'],
      tip='Without the final E it would read "invit" — the E is what makes it "vite".'),
 dict(t='butterflies', d='Insects with two pairs of large, often brightly patterned wings, that go through a caterpillar stage first.',
      ex='Orange and black butterflies gathered on the milkweed plant.',
      hint='BUTTER + FLIES — and FLY changes Y to I before -es.', sp='BUT-er-flyz',
      steps=['Two words joined: butter and flies.','B-U-T-T-E-R, double T.','"Fly" drops its Y and adds -ies: F-L-I-E-S.'],
      tip='"Fly" alone ends in Y, but the plural swaps that Y for I before -es.'),
 dict(t='kelp', d='A large brown seaweed that grows in cold coastal waters, sometimes forming underwater forests.',
      ex='Sea otters wrap themselves in kelp to keep from drifting out to sea.',
      hint='One syllable, straight through: K-E-L-P.', sp='kelp',
      steps=['One syllable, four letters.','K-E-L-P, no doubled letters.','Say it once, all the way through.'],
      tip='No silent letters and no tricks — it is spelled exactly how it sounds.'),
 dict(t='property', d='Something that belongs to a person, or the land and buildings someone owns.',
      ex='The old barn is still standing on their property.',
      hint='PROP- + -ER + -TY — three easy parts.', sp='PROP-er-tee',
      steps=['Three syllables: prop, er, ty.','P-R-O-P, one P.','Add E-R, then T-Y.'],
      tip='"Prop" only has one P even though the whole word sounds heavy.'),
 dict(t='carefully', d='Done with close attention, so as to avoid mistakes, damage, or danger.',
      ex='She carefully carried the stack of glass plates to the sink.',
      hint='CARE + FUL + LY — double L where "full" meets "ly".', sp='KAIR-ful-ee',
      steps=['Three parts: care, ful, ly.','C-A-R-E, keeping the silent E.','"full" drops one L before -ly: F-U-L, then L-Y.'],
      tip='"Full" has two Ls on its own, but loses one when -ly is added — the other L comes from -ly itself.'),
 dict(t='sniffling', d='Breathing in short, audible sniffs through the nose, often from crying or a cold.',
      ex='He came in sniffling and wiping his nose after the walk in the rain.',
      hint='Double F before -ling: SNIFF + LING.', sp='SNIF-ling',
      steps=['Start with "sniff": S-N-I-F-F.','Drop the final F is wrong — keep both Fs.','Add L-I-N-G.'],
      tip='"Sniff" keeps its double F all the way through, even with -ling attached.'),
 dict(t='beneath', d='In or to a lower position than something else; underneath.',
      ex='The cat curled up beneath the porch to stay cool.',
      hint='BE- + NEATH — "neath" is an old word for "under" on its own.', sp='bih-NEETH',
      steps=['Two syllables: be and neath.','B-E, then N-E-A-T-H.','The EA says a long E sound, like in "each".'],
      tip='"Neath" rhymes with "teeth" — same EA-TH pattern.'),
 dict(t='tractor', d='A powerful vehicle with large wheels, used to pull farm machinery or heavy loads.',
      ex='The farmer drove the tractor slowly along the fence line.',
      hint='TRACT- (like "traction") + -OR.', sp='TRAK-ter',
      steps=['Two syllables: tract and or.','T-R-A-C-T, same as "traction" without the -ion.','Finish with O-R, not E-R.'],
      tip='It ends in -OR like "actor" and "doctor", not -ER.'),
 dict(t='permit', d='To allow something to happen, or an official paper that gives permission for something.',
      ex='You need a permit to build a fence that tall.',
      hint='PER- + -MIT, like "permission" cut short.', sp='per-MIT',
      steps=['Two syllables: per and mit.','P-E-R, then M-I-T.','One T at the end, not two.'],
      tip='Related to "permission" and "permissible" — all share the same PER-M- start.'),
 dict(t='awning', d='A rooflike cover, often made of canvas or metal, that extends over a window, door, or patio.',
      ex='Rain drummed steadily on the striped awning above the café tables.',
      hint='AWN- + -ING — do not forget the N before -ing.', sp='AW-ning',
      steps=['Two syllables: awn and ing.','A-W-N, three letters before the ending.','Add I-N-G.'],
      tip='It is easy to drop the N by accident — say "awn" slowly to hear it.'),
 dict(t='fickle', d='Likely to change opinions, loyalty, or feelings suddenly and without warning.',
      ex='The weather this week has been fickle — sun one hour, rain the next.',
      hint='FICK- + -LE, and it rhymes with "pickle".', sp='FIK-ul',
      steps=['Two syllables: fick and le.','F-I-C-K, ending in CK like "pick".','Finish with L-E.'],
      tip='Rhyme it with "pickle" and the CK-LE pattern falls into place.'),
 dict(t='relief', d='A feeling of comfort or reassurance after worry, pain, or difficulty ends.',
      ex='Finding her lost keys brought a wave of relief.',
      hint='"I" before "E" except after "C" — so it is L-I-E-F.', sp='rih-LEEF',
      steps=['Two syllables: re and lief.','R-E, then L.','I before E: L-I-E-F.'],
      tip='No C anywhere in this word, so the ordinary I-before-E rule applies with no exception.'),
 dict(t='lunar', d='Relating to or connected with the moon.',
      ex="A lunar eclipse happens when Earth's shadow falls across the moon.",
      hint='LUN- (like "lunatic", which the Romans blamed on the moon) + -AR.', sp='LOO-ner',
      steps=['Two syllables: lun and ar.','L-U-N, same start as "lunatic".','Finish with A-R, not E-R.'],
      tip='It ends in -AR, matching "solar" — its opposite for the sun.'),
 dict(t='boycotting', d='Refusing to buy, use, or take part in something, as a form of organized protest.',
      ex='The neighborhood was boycotting the store until it lowered its prices.',
      hint='BOYCOTT doubles the T before -ING.', sp='BOI-kot-ing',
      steps=['Start with "boycott": B-O-Y-C-O-T-T.','Double T stays before the ending.','Add I-N-G.'],
      tip='"Boycott" already ends in double T on its own — -ing does not add a third.'),
 dict(t='molten', d='Melted by great heat, especially describing rock or metal in liquid form.',
      ex="Molten lava glowed orange as it flowed down the volcano's side.",
      hint='MOLT- + -EN, like "melt" with a different vowel.', sp='MOHL-tun',
      steps=['Two syllables: molt and en.','M-O-L-T, an O not an E.','Finish with E-N.'],
      tip='It looks like "melt" but the vowel changes to O — say it slowly to hear the difference.'),
 dict(t='elite', d='A select, small group of people considered the best, most skilled, or most powerful in their field.',
      ex='Only the elite runners qualified for the final race.',
      hint='One L, then -LITE, like "light" without the GH.', sp='ih-LEET',
      steps=['Two syllables: e and lite.','E, one letter.','L-I-T-E — one L, silent E at the end.'],
      tip='Just one L in the middle — doubling it is the most common slip.'),
 dict(t='woven', d='Formed by crossing threads or strips over and under one another, as cloth or a basket is made.',
      ex='The basket was woven from thin strips of willow.',
      hint='WOVE (past tense of "weave") + -N.', sp='WOH-vun',
      steps=['Two syllables: wo and ven.','W-O-V-E, like "wove".','Add N at the end.'],
      tip='"Weave" becomes "wove" in the past tense, and "woven" just adds N to that.'),
 dict(t='proclaim', d='To announce something officially and publicly, often with importance or authority.',
      ex="The mayor stood on the steps to proclaim the city's new holiday.",
      hint='PRO- + CLAIM — "claim" hides right inside it.', sp='proh-KLAYM',
      steps=['Two syllables: pro and claim.','P-R-O.','"Claim" spells exactly as you already know it: C-L-A-I-M.'],
      tip='If you can spell "claim", you already know the second half of this word.'),
 dict(t='thimble', d='A small protective cap, usually metal, worn on the finger to push a needle while sewing.',
      ex='Grandma always kept a silver thimble in her sewing box.',
      hint='THIM- + -BLE, starting with the same TH as "thumb" — where it goes.', sp='THIM-bul',
      steps=['Two syllables: thim and ble.','T-H-I-M, same TH as "thumb".','Finish with B-L-E.'],
      tip='A thimble protects the thumb or finger — both words share that TH start.'),
 dict(t='custody', d='The legal right and responsibility to care for and protect someone, or the state of being guarded.',
      ex='After the divorce, the parents shared custody of their two children.',
      hint='CUS- + TO- + DY — "custo" starts like "custom".', sp='KUS-tuh-dee',
      steps=['Three syllables: cus, to, dy.','C-U-S, same start as "custom".','Add T-O-D-Y.'],
      tip='"Custom" and "custody" share their first four letters exactly.'),
 dict(t='granola', d='A breakfast and snack food made of rolled oats mixed with nuts, dried fruit, and a sweetener, often baked crisp.',
      ex='She packed a bag of granola for the hike.',
      hint='GRAN- (like "grain") + -OLA.', sp='gruh-NOH-luh',
      steps=['Three syllables: gra, no, la.','G-R-A-N, like "grain" without the I.','Finish with O-L-A.'],
      tip='It starts like "grain" — the food it is mostly made from.'),
 dict(t='warrior', d='A person who fights in battles, especially one known for courage or skill; a brave fighter.',
      ex='Ancient stories often describe a lone warrior defending the village.',
      hint='WAR- + -RIOR — double R sits before -ior.', sp='WAWR-ee-er',
      steps=['Three syllables: war, ri, or.','W-A-R, the word "war" itself.','Double the R, then add I-O-R.'],
      tip='It starts with the whole word "war" — the fighting it describes.'),
 dict(t='rigid', d='Stiff and unable to bend, or — for a rule or person — very strict and unwilling to change.',
      ex='The metal rod stayed perfectly rigid even under heavy weight.',
      hint='RIG- + -ID, one G, not two.', sp='RIJ-id',
      steps=['Two syllables: rig and id.','R-I-G, just one G.','Finish with I-D.'],
      tip='The G sounds soft, like a J, but it is still spelled with a plain G.'),
 dict(t='fierce', d='Showing intense, powerful energy or aggression; wild and forceful.',
      ex='A fierce wind bent the young trees nearly to the ground.',
      hint='"I" before "E" — FIERCE rhymes with "pierce".', sp='feers',
      steps=['One syllable, five letters.','F, then I before E: F-I-E.','Finish with R-C-E — the soft C sound needs that final E.'],
      tip='Rhymes exactly with "pierce" — same I-E-R-C-E ending.'),
 dict(t='laughter', d='The action or sound of laughing, usually in response to something funny or joyful.',
      ex='Laughter filled the room as the puppy chased its own tail.',
      hint='LAUGH (the GH sounds like an F) + -TER.', sp='LAF-ter',
      steps=['Two syllables: laugh and ter.','L-A-U-G-H — the GH makes an F sound.','Add T-E-R.'],
      tip='"Laugh" keeps its silent-looking GH even inside a longer word.'),
 dict(t='salary', d='A fixed amount of money paid regularly, usually monthly or yearly, for doing a job.',
      ex='Her new salary let her start saving for college.',
      hint='SAL- + -A- + -RY — three syllables, one L.', sp='SAL-uh-ree',
      steps=['Three syllables: sal, a, ry.','S-A-L, just one L.','Finish with A-R-Y.'],
      tip='Only one L, even though the first syllable is stressed hard.'),
 dict(t='disappear', d='To stop being visible; to vanish from sight completely.',
      ex='The rabbit seemed to disappear into the tall grass.',
      hint='DIS- + APPEAR — one S in "dis", double P in "appear".', sp='dis-uh-PEER',
      steps=['Two parts: dis and appear.','D-I-S, one S.','"Appear" has double P: A-P-P-E-A-R.'],
      tip='The prefix DIS- has one S; the double letter is the P inside "appear".'),
 dict(t='hurdler', d='An athlete who runs and jumps over a series of barriers, called hurdles, in a race.',
      ex='The hurdler cleared every barrier without knocking one down.',
      hint='HURDLE (the barrier) + -R, no extra E.', sp='HUR-dler',
      steps=['Start with "hurdle": H-U-R-D-L-E.','Drop nothing — just add R.','H-U-R-D-L-E-R.'],
      tip='It is "hurdle" plus one letter, R, at the very end.'),
 dict(t='lounge', d='A comfortable room for sitting and relaxing, or the act of sitting or lying back in a relaxed way.',
      ex='They chose to lounge by the pool instead of hiking that afternoon.',
      hint='LOUNGE rhymes with "sponge" — the E keeps the G soft.', sp='lownj',
      steps=['One syllable, six letters.','L-O-U-N-G.','Add a final E to keep the G sound soft.'],
      tip='Without the E, "loung" would look like it should end hard — the E is what makes it say "-nj".'),
 dict(t='jovial', d='Cheerful, friendly, and full of good humor.',
      ex='The jovial shopkeeper greeted every customer with a joke.',
      hint='JOVI- (from Jove, another name for the god linked to good fortune) + -AL.', sp='JOH-vee-ul',
      steps=['Three syllables: jo, vi, al.','J-O-V-I, no double letters.','Finish with A-L.'],
      tip='Named after Jove/Jupiter — old astrologers thought that planet brought good cheer.'),
 dict(t='inferior', d='Lower in rank, status, or quality compared to something or someone else.',
      ex='The reviewer said the cheap copy felt inferior to the original.',
      hint='IN- + FERIOR — it pairs with its opposite, "superior".', sp='in-FEER-ee-er',
      steps=['Four syllables: in, fe, ri, or.','I-N, then F-E-R-I.','Finish with O-R.'],
      tip='"Inferior" and "superior" share the same -FERIOR/-PERIOR-style ending pattern.'),
 dict(t='December', d='The twelfth and final month of the year, marking the start of winter in the Northern Hemisphere.',
      ex='Snow usually starts falling here by mid-December.',
      hint='Capital D, then DE- + CEM- + -BER — "cem" rhymes with "gem".', sp='dih-SEM-ber',
      steps=['Three syllables: de, cem, ber.','Capital D, then E.','C-E-M, then B-E-R.'],
      tip='Months are always capitalized, and the middle syllable rhymes with "gem" and "stem".'),
 dict(t='duration', d='The length of time that something lasts or continues.',
      ex="The movie's duration was just over two hours.",
      hint='DUR- (like "during") + -ATION.', sp='dur-AY-shun',
      steps=['Three syllables: du, ra, tion.','D-U-R, same start as "during".','Finish with A-T-I-O-N.'],
      tip='The -TION ending always sounds like "shun" — a pattern shared with "nation" and "station".'),
 dict(t='dictionary', d='A reference book that lists words in alphabetical order along with their meanings and pronunciations.',
      ex='She looked up the unfamiliar word in the dictionary.',
      hint='DICTION- (the way words are spoken) + -ARY.', sp='DIK-shuh-ner-ee',
      steps=['Four syllables: dic, tion, a, ry.','D-I-C-T-I-O-N, same as the word "diction".','Finish with A-R-Y.'],
      tip='"Diction" means the way words are said — a dictionary is where you look them up.'),
 dict(t='business', d="A person's regular work or trade, or an organization that makes, buys, or sells goods and services.",
      ex='Their family business has sold bicycles for three generations.',
      hint='BUSI- (from "busy") + -NESS — the U makes an "i" sound.', sp='BIZ-nis',
      steps=['Three syllables: busi, ness — said as two: BIZ-nis.','B-U-S-I, from the word "busy".','Add N-E-S-S.'],
      tip='It looks like it should say "BUS-i-ness", but it comes from "busy" and sounds like "BIZ-nis".'),
 dict(t='reinstate', d='To restore someone or something to a former position, condition, or state.',
      ex='The committee voted to reinstate the canceled holiday.',
      hint='RE- + IN- + STATE — three small words joined.', sp='ree-in-STAYT',
      steps=['Three parts: re, in, state.','R-E, then I-N.','Finish with S-T-A-T-E, the word "state" itself.'],
      tip='"State" keeps its own spelling exactly, with RE- and IN- stacked in front.'),
 dict(t='examine', d="To inspect something carefully and in detail, or to test someone's knowledge.",
      ex="The doctor took a moment to examine the small cut on her hand.",
      hint='EX- + AMINE, one M — like "exam" with -ine added.', sp='ig-ZAM-in',
      steps=['Three syllables: ex, am, ine.','E-X-A-M, the word "exam" itself.','Finish with I-N-E.'],
      tip='"Exam" is short for "examination" — this word is the verb they both come from.'),
 dict(t='versus', d='Against, used to describe two sides opposing each other, especially in a contest, game, or legal case.',
      ex="Friday's game is the home team versus their biggest rivals.",
      hint='VERSUS is its own whole word — one S in the middle, one at the end.', sp='VER-sus',
      steps=['Two syllables: ver and sus.','V-E-R-S, one S in the middle.','Finish with U-S.'],
      tip='It is a full word on its own — not an abbreviation, even though it is often shortened to "vs." in print.'),
 dict(t='lullaby', d='A soft, soothing song sung to help a baby or young child fall asleep.',
      ex='Her grandmother hummed the same lullaby every night before bed.',
      hint='LULL (to calm) + -A- + -BY.', sp='LUL-uh-by',
      steps=['Three syllables: lull, a, by.','L-U-L-L, double L, from the word "lull".','Finish with A-B-Y.'],
      tip='"Lull" means to calm gently — exactly what a lullaby does.'),
 dict(t='opposite', d='Situated on the other side of something, or completely different in nature or direction.',
      ex='North is the exact opposite direction from south.',
      hint='OPPO- (double P) + -SITE.', sp='OP-uh-zit',
      steps=['Three syllables: op, po, site.','O-P-P, double P.','Finish with O-S-I-T-E.'],
      tip='The double P is the part most often forgotten — say "op-po" slowly to hear both.'),
 dict(t='tissues', d='Soft, absorbent paper used for wiping or blowing the nose, or the biological material that makes up living things.',
      ex='He grabbed a box of tissues before his nose started running.',
      hint='TISSUE keeps its U even though you do not hear it — TIS- + -SUE.', sp='TISH-ooz',
      steps=['Start with "tissue": T-I-S-S-U-E, double S.','The U is silent but still there.','Add S for the plural: tissues.'],
      tip='"Tissue" has a silent U right before the E — easy to drop by accident.'),
 dict(t='marlin', d='A large, fast ocean fish with a long, spear-shaped upper jaw, prized by sport fishers.',
      ex="The fishing boat's crew spotted a marlin leaping near the horizon.",
      hint='MAR- (like the start of "marine") + -LIN.', sp='MAR-lin',
      steps=['Two syllables: mar and lin.','M-A-R, same start as "marine".','Finish with L-I-N.'],
      tip='Not "marlyn" or "marlen" — it ends plainly in -LIN.'),
]

assert len(WORDS) == 50, len(WORDS)

def build_lesson(words, n, listno):
    C, Q = [], []
    for w in words:
        card(C, w['t'], '**' + w['d'] + '**\n• ' + w['ex'], hint=w['hint'], frm='added')
        C[-1]['sp'] = w['sp']
        prompt = 'Spell the word: ' + w['d'][0].lower() + w['d'][1:].rstrip('.') + '.'
        q(Q, 1, prompt, [w['t']], 0, w['hint'],
          w['steps'] + [w['t'].upper()], '**' + w['t'] + '.**', w['tip'], frm='added', kind='spell')
    build('wayfinder', C, Q, 'unit-bee%d' % listno, 'Spelling Bee · List %d' % listno, 'english',
          'List %d of River\'s Spelling Bee study words: %s.' % (listno, ', '.join(w['t'] for w in words)),
          'This is the real Scripps "Two Bee" fourth-grade word list — the words a school spelling bee actually draws from. Saying each word aloud, letter by letter, is the same skill a real bee tests, not just recognizing the word on a page.',
          [('Spell every word on this list correctly, letter by letter, from hearing it alone.', 'added'),
           ('State each word\'s meaning in your own words.', 'added')],
          'Built from "Spelling Bee Words", the 2026-27 Scripps Two Bee fourth-grade study list you added to her Drive folder. All 50 official words are split across four lessons; every definition and example sentence here was written fresh, since the source is a bare word list with no definitions to copy. The flashcards use the honeycomb "bee" look, and each lesson also opens the Spelling Bee voice game — hear it, spell it aloud letter by letter.',
          ('Cards first to learn the meanings, then the Spelling Bee game to practice saying the letters aloud.', 12),
          'content/spelling-bee-%d.json' % listno, SRC, SRCLONG, round_=n, bee_=True)

build_lesson(WORDS[0:13], 13, 1)
build_lesson(WORDS[13:26], 13, 2)
build_lesson(WORDS[26:38], 12, 3)
build_lesson(WORDS[38:50], 12, 4)
print('--- spelling bee: all 4 lists built ---')
